### ISSUE TITLE
description은 화면에 표출되지 않게 하는게 어떤가요

### ISSUE THREAD

**Issue by amin7942** [OSS2023TP/project#5]
<img width="712" alt="수정요청" src="https://github.com/OSS2023TP/project/assets/76994595/ab73bebd-9a65-43f3-a045-f2f8f0096300">
저게 만약 내용이 길면 보기 안좋을 것 같아요

**Comment by amin7942** [comment]
Task조회를 선택했을때 저 메뉴에서 description만 제외하고 보여 준 다음,  자세히 보려면 1번을 누르세요.아니면0번을 누르세요. 하고 1번을 누르면 그때서야 description도 같이 보여주는걸로요

**Comment by JewooJun** [comment]
Description이 길어진다면 그렇게 하는 것이 조금 더 깔끔할 것 같네요 그렇게 해봅시다

**Comment by JewooJun** [comment]
9번에서 자세히 보기란에서 모든 항목을 엔터로 구분한다면 더 보기 좋을 것 같습니다. 수정 후 올리도록 하겠습니다.

**Comment by JewooJun** [comment]
9번 함수 수정과 메뉴란을 비롯한 다른 출력 형태 보기 좋게 수정하여 push 하였습니다.

**Comment by JewooJun** [comment]
이 이슈는 해결되어 닫도록 할게요.
